# Generated by Django 5.0.6 on 2024-08-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
