# Generated by Django 5.0.6 on 2024-08-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_user_last_login_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
